=== googlecode-mirror/balrog/trunk/xsd/forms.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/forms"
	xmlns:tns="http://www.example.org/forms"
	elementFormDefault="qualified">
	<complexType name="forms">
		<sequence>
			<element name="form" type="string" maxOccurs="unbounded"
				minOccurs="1">
			</element>

		</sequence>
	</complexType>
	<complexType name="form">
		<sequence>
			<element name="action" type="tns:action" maxOccurs="1" minOccurs="1"></element>
			<element name="name" type="tns:name" maxOccurs="1" minOccurs="0"></element>
			<element name="fields" type="tns:fields" maxOccurs="unbounded" minOccurs="1"></element>
		</sequence>
	</complexType>
	<simpleType name="action">
		<restriction base="string"></restriction>
	</simpleType>

	<simpleType name="name">
		<restriction base="string"></restriction>
	</simpleType>

	<complexType name="fields">
		<sequence>
			<element name="field" type="tns:field" maxOccurs="unbounded" minOccurs="1"></element>
		</sequence>
	</complexType>

	<complexType name="field">
		<sequence>
			<element name="type" type="tns:type" maxOccurs="1"
				minOccurs="1">
			</element>
			<element name="name" type="tns:name" maxOccurs="1"
				minOccurs="1">
			</element>
            <element name="label" type="tns:label" maxOccurs="1" minOccurs="0"></element>
            <element name="options" type="tns:options" maxOccurs="1"
				minOccurs="0">
			</element>
			<element name="validations" type="tns:validations"
				maxOccurs="1" minOccurs="0">
			</element>
		</sequence>
	</complexType>

	<simpleType name="label">
		<restriction base="string"></restriction>
	</simpleType>

	<simpleType name="type">
		<list itemType="string">
			<enumeration value="checkbox"></enumeration>
			<enumeration value="checkboxes"></enumeration>
			<enumeration value="radio list"></enumeration>
			<enumeration value="radio"></enumeration>
			<enumeration value="text"></enumeration>
			<enumeration value="textarea"></enumeration>
			<enumeration value="select"></enumeration>
			<enumeration value="file"></enumeration>
		</list>
	</simpleType>


	<complexType name="options">
		<sequence>
			<element name="option" type="tns:option" maxOccurs="unbounded" minOccurs="1"></element>
		</sequence>
	</complexType>

	<complexType name="option">
		<sequence>
			<element name="value" type="tns:value" maxOccurs="1" minOccurs="0"></element>
			<element name="label" type="tns:label" maxOccurs="1" minOccurs="1"></element>
		</sequence>
	</complexType>

	<simpleType name="value">
		<restriction base="string"></restriction>
	</simpleType>


	<element name="forms" type="tns:forms"></element>

	<element name="form" type="tns:form"></element>

	<element name="fields" type="tns:fields"></element>

	<element name="field" type="tns:field"></element>

	<complexType name="validations">
		<sequence>
			<element name="validation" type="tns:validation" maxOccurs="unbounded" minOccurs="1"></element>
		</sequence>
	</complexType>
	
    <element name="options" type="tns:options"></element>

    <element name="option" type="tns:option"></element>

    <element name="validations" type="tns:validations"></element>

    <simpleType name="validation">
    	<list itemType="string">
    		<enumeration value="email"></enumeration>
    		<enumeration value="numeric"></enumeration>
    		<enumeration value="alphanumeric"></enumeration>
    	</list>
    </simpleType>
</schema>

=== googlecode-mirror/balrog/trunk/views/xml/form1.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../xsl/template.xsl"?>
<uvcms:form xmlns:uvcms="http://www.uvcms.com/forms"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.uvcms.com/forms ../xsd/forms.xsd ">
	<uvcms:action>?a=process</uvcms:action>
	<uvcms:fields>
		<uvcms:field>
			<uvcms:type>text</uvcms:type>
			<uvcms:name>firstname</uvcms:name>
			<uvcms:label>First Name</uvcms:label>
		</uvcms:field>
		<uvcms:field>
			<uvcms:type>text</uvcms:type>
			<uvcms:name>lastname</uvcms:name>
			<uvcms:label>Last Name</uvcms:label>
		</uvcms:field>
		<uvcms:field>
			<uvcms:type>textarea</uvcms:type>
			<uvcms:name>description</uvcms:name>
			<uvcms:label>Description</uvcms:label>
		</uvcms:field>
		<uvcms:field>
			<uvcms:type>radio</uvcms:type>
			<uvcms:name>sex</uvcms:name>
			<uvcms:label>Sex</uvcms:label>
			<uvcms:options>
				<uvcms:option>
					<uvcms:value>1</uvcms:value>
					<uvcms:label>M</uvcms:label>
				</uvcms:option>
				<uvcms:option>
					<uvcms:value>2</uvcms:value>
					<uvcms:label>F</uvcms:label>
				</uvcms:option>
			</uvcms:options>
		</uvcms:field>

		<uvcms:field>
			<uvcms:type>checkboxes</uvcms:type>
			<uvcms:name>interests</uvcms:name>
			<uvcms:label>Insterests</uvcms:label>
			<uvcms:options>
				<uvcms:option>
					<uvcms:value>1</uvcms:value>
					<uvcms:label>Internet</uvcms:label>
				</uvcms:option>
				<uvcms:option>
					<uvcms:value>2</uvcms:value>
					<uvcms:label>Sports</uvcms:label>
				</uvcms:option>
				<uvcms:option>
					<uvcms:value>3</uvcms:value>
					<uvcms:label>Food</uvcms:label>
				</uvcms:option>
			</uvcms:options>
		</uvcms:field>
		<uvcms:field>
			<uvcms:type>submit</uvcms:type>
			<uvcms:name>submit</uvcms:name>
			<uvcms:label>Enviar</uvcms:label>
		</uvcms:field>
	</uvcms:fields>
</uvcms:form>

=== googlecode-mirror/balrog/views/xml/form2.xml
<?xml version="1.0" encoding="UTF-8"?>
<uvcms:form xmlns:uvcms="http://www.uvcms.com/forms" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.uvcms.com/forms ../xsd/forms.xsd ">
  <uvcms:action>uvcms:action</uvcms:action>
  <uvcms:fields>
    <uvcms:field>
      <uvcms:type>text</uvcms:type>
      <uvcms:name>title</uvcms:name>
      <uvcms:label>Title</uvcms:label>
    </uvcms:field>
    <uvcms:field>
    	<uvcms:type>textarea</uvcms:type>
    	<uvcms:name>body</uvcms:name>
    	<uvcms:label>Body</uvcms:label>
    </uvcms:field>
    <uvcms:field>
    	<uvcms:type>submit</uvcms:type>
    	<uvcms:name>submit</uvcms:name>
    	<uvcms:label>Send</uvcms:label>
    </uvcms:field>
  </uvcms:fields>
</uvcms:form>

=== googlecode-mirror/balrog/views/xml/form1.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://localhost/balrog/views/xsl/template.xsl"?>
<uvcms:forms xmlns:uvcms="http://www.uvcms.com/forms"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.uvcms.com/forms ../xsd/forms.xsd ">
	<uvcms:form>
		<uvcms:action>http:\\soydewilde.com.ar</uvcms:action>
		<uvcms:fields>
			<uvcms:field>
				<uvcms:type>text</uvcms:type>
				<uvcms:name>nombre</uvcms:name>
				<uvcms:label>Nombre</uvcms:label>
			</uvcms:field>
			<uvcms:field>
				<uvcms:type>text</uvcms:type>
				<uvcms:name>apellido</uvcms:name>
				<uvcms:label>Apellido</uvcms:label>
			</uvcms:field>
			<uvcms:field>
				<uvcms:type>radio</uvcms:type>
				<uvcms:name>sexo</uvcms:name>
				<uvcms:label>Sexo</uvcms:label>
				<uvcms:options>
					<uvcms:option>
						<uvcms:value>1</uvcms:value>
						<uvcms:label>M</uvcms:label>
					</uvcms:option>
					<uvcms:option>
						<uvcms:value>2</uvcms:value>
						<uvcms:label>F</uvcms:label>
					</uvcms:option>
				</uvcms:options>
			</uvcms:field>
			<uvcms:field>
				<uvcms:type>submit</uvcms:type>
				<uvcms:name>submit</uvcms:name>
				<uvcms:label>Mandar</uvcms:label>
			</uvcms:field>
		</uvcms:fields>
	</uvcms:form>
</uvcms:forms>
