=== googlecode-mirror/balrog/dtd/forms.dtd
<!ELEMENT forms (form+)>
<!ELEMENT form (name?, id?, action, fields)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT action (#PCDATA)>
<!ELEMENT fields (field+)>
<!ELEMENT field (type, name, label, options?, validations?)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT label (#PCDATA)>
<!ELEMENT options (option+)>
<!ELEMENT option (value?, label)>
<!ELEMENT value (#PCDATA)>
<!ELEMENT validations (validation+)>
<!ELEMENT validation (#PCDATA)>

=== googlecode-mirror/balrog/trunk/xml/myform3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE forms SYSTEM "../dtd/forms.dtd" >
<forms>
  <form>
    <action>www.soydewilde.com.ar</action>
    <fields>
      <field>
        <type>type</type>
        <name>name</name>
        <label>label</label>
        <validations>
        	<validation>validation</validation>
        </validations>
      </field>
    </fields>
  </form>
</forms>

=== googlecode-mirror/balrog/xml/myform2.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../xsl/html.template.xsl"?>
<!DOCTYPE forms SYSTEM "../dtd/forms.dtd">
<forms>
  <form>
    <action>www.google.com</action>
    <fields>
      <field>
        <type>text</type>
        <name>nombre</name>
        <label>Nombre</label>
      </field>
      <field>
      	<type>type</type>
      	<name>name</name>
      	<label>label</label>
      </field>
    </fields>
  </form>
</forms>

=== googlecode-mirror/balrog/xml/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE forms SYSTEM "../dtd/forms.dtd" >
<forms>
  <form>
    <action>action</action>
    <fields>
      <field>
        <type>type</type>
        <name>name</name>
        <label>label</label>
      </field>
    </fields>
  </form>
</forms>

=== googlecode-mirror/balrog/trunk/inc/xml/myform2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE forms SYSTEM "../dtd/forms.dtd">
<forms>
  <form>
    <action>www.google.com</action>
    <fields>
      <field>
        <type>type</type>
        <name>caca</name>
        <label>pupu</label>
      </field>
      <field>
      	<type>type</type>
      	<name>name</name>
      	<label>label</label>
      </field>
    </fields>
  </form>
</forms>

=== googlecode-mirror/balrog/trunk/inc/xml/myform.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE forms SYSTEM "../dtd/forms.dtd">
<forms>
	<form>
		<action>www.soydewilde.com.ar</action>
		<fields>
			<field>
				<type>text</type>
				<name>email</name>
				<label>Email</label>
				<validations>
					<validation>required</validation>
					<validation>email</validation>
				</validations>
			</field>
			<field>
				<type>select</type>
				<name>temperaturas</name>
				<label>Select</label>
				<options>
					<option>
						<value>1</value>
						<label>frio</label>
					</option>
					<option>
						<value>2</value>
						<label>tibio</label>
					</option>
					<option>
						<value>3</value>
						<label>caliente</label>
					</option>
				</options>
			</field>
			<field>
				<type>radio</type>
				<name>numeros</name>
				<label>Radio Buttons</label>
				<options>
					<option>
						<value>10</value>
						<label>diez</label>
					</option>
					<option>
						<value>20</value>
						<label>veinte</label>
					</option>
					<option>
						<value>30</value>
						<label>treinta</label>
					</option>
				</options>
			</field>
			<field>
				<type>checkboxes</type>
				<name>colores</name>
				<label>Checkboxes</label>
				<options>
					<option>
						<value>1</value>
						<label>verde</label>
					</option>
					<option>
						<value>2</value>
						<label>azul</label>
					</option>
					<option>
						<value>3</value>
						<label>rojo</label>
					</option>
				</options>
			</field>
		</fields>
	</form>
</forms>

=== googlecode-mirror/balrog/xml/myform.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../xsl/html.template.xsl"?>
<!DOCTYPE forms SYSTEM "../dtd/forms.dtd">
<forms>
	<form>
		<action>www.soydewilde.com.ar</action>
		<fields>
			<field>
				<type>text</type>
				<name>email</name>
				<label>Email</label>
				<validations>
					<validation>required</validation>
					<validation>email</validation>
				</validations>
			</field>
			<field>
				<type>select</type>
				<name>temperaturas</name>
				<label>Select</label>
				<options>
					<option>
						<value>1</value>
						<label>frio</label>
					</option>
					<option>
						<value>2</value>
						<label>tibio</label>
					</option>
					<option>
						<value>3</value>
						<label>caliente</label>
					</option>
				</options>
			</field>
			<field>
				<type>radio</type>
				<name>numeros</name>
				<label>Radio Buttons</label>
				<options>
					<option>
						<value>10</value>
						<label>diez</label>
					</option>
					<option>
						<value>20</value>
						<label>veinte</label>
					</option>
					<option>
						<value>30</value>
						<label>treinta</label>
					</option>
				</options>
			</field>
			<field>
				<type>checkboxes</type>
				<name>colores</name>
				<label>Checkboxes</label>
				<options>
					<option>
						<value>1</value>
						<label>verde</label>
					</option>
					<option>
						<value>2</value>
						<label>azul</label>
					</option>
					<option>
						<value>3</value>
						<label>rojo</label>
					</option>
				</options>
			</field>
			<field>
				<type>checkbox</type>
				<name>boolean</name>
				<label>True/False</label>
			</field>
			<field>
				<type>file</type>
				<name>file</name>
				<label>Add File</label>
			</field><field>
				<type>submit</type>
				<name>send</name>
				<label></label>
			</field>
			
		</fields>
	</form>
</forms>
